[mysqld]

basedir=D:/OnokasirLocal/mariadb
datadir=D:/OnokasirLocal/mariadb/data

port=3306
bind-address=127.0.0.1

character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

default-storage-engine=InnoDB

log-error=D:/OnokasirLocal/mariadb/logs/mariadb-error.log

max_connections=100